apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keda-demo
resources:
  - namespace.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - worker-deployment.yaml
  - scaledobject.yaml
