apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: hello-cron
  namespace: keda-test
spec:
  scaleTargetRef:
    name: hello
  minReplicaCount: 0
  maxReplicaCount: 3
  triggers:
    - type: cron
      metadata:
        timezone: Etc/UTC
        start: "0 * * * *"
        end: "5 * * * *"
        desiredReplicas: "1"
