apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Installs KEDA v2.17.2 core components (CRDs + operator + metrics-apiserver)
resources:
  - https://github.com/kedacore/keda/releases/download/v2.17.2/keda-2.17.2-core.yaml
