apiVersion: v1
kind: Service
metadata:
  name: functions-runtime
  labels:
    app: functions-runtime
spec:
  selector:
    app: functions-runtime
  ports:
    - name: http
      port: 80
      targetPort: 8080
