apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Installs KEDA v2.17.2 (CRDs + operator + metrics-apiserver + webhooks)
resources:
  - https://github.com/kedacore/keda/releases/download/v2.17.2/keda-2.17.2.yaml
